@startuml 図書館システムクラス図
skinparam classAttributeIconSize 0

class 図書館
class 事務職員

class 利用者 {
  -会員番号
  +貸出予約()
  +貸出履歴()
  +貸出通知()
}

class 学生 {
  -学生番号
}

class 教職員 {
  -教員番号
}

class 本 {
  -管理番号
  -書名
}

class 書籍 {
}

class 雑誌 {
}

class 貸出予約 {
  -予約ID
  -予約日
}

class 貸出履歴 {
  -履歴ID
  -貸出日
  -返却日
}

class 貸出通知 {
  -通知ID
  -通知日
}

図書館 -- 事務職員
図書館 -- 利用者

利用者 <|-- 学生
利用者 <|-- 教職員

本 <|-- 書籍
本 <|-- 雑誌

利用者 -- 貸出予約
利用者 -- 貸出履歴
利用者 -- 貸出通知
貸出予約 -- 本
貸出履歴 -- 本
貸出通知 -- 事務職員

@enduml