@startuml
hide footbox

actor 事務職員 as A
boundary システムメニュー as B1
boundary 図書貸出画面 as B2
boundary 会員情報 as E1
control 貸出処理 as C1
control 貸出確認処理 as C2
control 図書削除 as C3
control 貸出一覧表示画面処理 as C4
entity 図書情報 as E2
boundary 貸出完了画面 as B3

A -> B1 : 貸出メニューをクリック
B1 -> B2 : 貸出画面表示

A -> B2 : 会員番号を入力
B2 -> C1 : 会員番号入力検知処理
C1 -> E1 : 会員情報表示
alt 会員番号未入力または未登録
    C1 -> B2 : 「会員番号を確認してください」メッセージ表示
end

A -> B2 : 管理番号入力
B2 -> C2 : 管理番号入力検知処理
C2 -> E2 : 管理番号検索
alt 管理番号未入力または未登録
    C2 -> B2 : 「管理番号を確認してください」メッセージ表示
else 貸出上限超過 or 学生に雑誌貸出
    C2 -> B2 : 貸出不可理由メッセージ表示
end

A -> B2 : キャンセルボタンをクリック
B2 -> C3 : 図書キャンセル依頼

A -> B2 : 貸出をクリック
B2 -> C1 : 貸出確定依頼
alt 一冊も確定していない
    C1 -> B2 : 「貸し出す書籍を入力してください」メッセージ表示
else 貸出確定
    C1 -> E1 : 貸出履歴保存
    C1 -> E2 : 図書状態更新
    C1 -> B3 : 貸出完了画面表示
end


@enduml
