@startuml BBショップ注文管理システム
skinparam classAttributeIconSize 0
hide circle
hide empty members

class ユーザー {
  -ユーザーID: int
  -名前: string
  -メールアドレス: string
  -電話番号: string
  -住所: string
  -パスワード: string

  +ログインする()
  +ログアウトする()
  +商品を購入する()
  +返品依頼をする()
  +商品の一覧を閲覧できる()
  +商品を検索できる()
  +配送状況を確認できる()
  
}

class 管理者 {
  -管理者ID: int
  -名前: string
  -種別: string
  -注文履歴: string

  +ログインする()
  +ログアウトする()
  +顧客情報を参照する()

}

class 商品 {
  -商品ID: int
  -商品情報: string
  -価格: float
  -在庫数: int

  +商品を登録できる()
  +商品を更新できる()
  +商品を削除できる()
  +在庫を確認できる()
}

class カート {
  -ユーザーID: int
  -商品ID: int
  -数量: int

  +カートに追加する()
}


class 注文 {
  -注文ID: int
  -ユーザーID: int
  -注文日: datetime
  -出荷状況ID: int
  -注文種別ID: int

  +注文履歴を確認する()
  +出荷状況更新する()
}

class 注文詳細 {
  -注文ID: int
  -商品ID: int
  -個数: int
  -小計: float
}

class 決済ログ {
  -決済ID: int
  -注文ID: int
  -決済金額: float
  -決済日: datetime
}

class 配送 {
  -配送先名: string
  -配送時間選択: datetime
  -配達日時: datetime

  +配送を手配する()
}

class 返品 {
  -返品ID: int
  -注文ID: int
  -理由: string
  -商品名: int
  -返品日時: datetime
  -返金額: float
}

class 出荷状況 {
    -状況名: string
}

class 種別 {
    -倉庫管理者
    -注文管理者
    -カスタマーサポート

    +出荷指示を確認する()
    +顧客問い合わせをする()    
    +返品処理をする()    

}

ユーザー "1" -- "0..*" カート
カート "0..*" -- "1" 商品
ユーザー "1" -- "0..*" 注文

注文 "1" -- "1..*" 注文詳細
注文詳細 "0..*" -- "1" 商品

注文 "1" -- "0..*" 決済ログ
注文 "1" -- "0..1" 配送
注文 "1" -- "0..*" 返品

注文 "0..*" -- "1" 出荷状況

管理者 "1" -- "1" 種別

@enduml