@startuml bbショップドメインモデル図
skinparam componentStyle rectangle

[管理者] o-- [管理者ID]
[管理者] o-- [注文履歴]
[管理者] o-- [名前]
' [管理者] -- [返品]
[管理者] o-- [種別]
[種別] o-- [倉庫管理者]
[種別] o-- [注文管理者]
[種別] o-- [カスタマーサポート]
[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [パスワード]
[ユーザー] o-- [名前]
[ユーザー] o-- [住所]
[ユーザー] o-- [メールアドレス]
[ユーザー] o-- [電話番号]
[ユーザー] -- [カート]

' 注文
[注文] o-- [合計金額]
[注文] o-- [注文ID]
[注文] o-- [注文日時]
[注文] o-- [注文詳細]
[注文] o-- [出荷状況]
[注文] o-- [入金状況]

' 入金状況
[入金状況] <|-- [入金済み]
[入金状況] <|-- [未入金]


' 注文詳細
[注文詳細] o-- [商品]
[注文詳細] o-- [個数]
[注文詳細] o-- [小計]


' 配送
[配送] o-- [注文]
[配送] o-- [住所]
[配送] o-- [配送日時]
[配送] o-- [配送先名]
[配送] o-- [配送時間帯選択]

' カート
[カート] o-- [数量]
[カート] o-- [商品]

' 商品
[商品] o-- [商品ID]
[商品] o-- [商品情報]
[商品] o-- [在庫数]
[商品] o-- [価格]

' 返品
[返品] o-- [返品理由]
[返品] o-- [返品ID]
[返品] o-- [返品日時]
[返品] o-- [商品名]
' [返品] o-- [注文ID]注文詳細でいいのかも
[返品] -- [返金金額]
[返品] -- [注文詳細]

' 返品理由
[返品理由] <|-- [販売者都合]
[返品理由] <|-- [購入者都合]

' 販売者都合
[販売者都合] <|-- [欠陥品]

' 購入者都合
[購入者都合] <|-- [商品が気に入らなかった]

' 返金
' [返金] o-- [返金金額]

' 注文履歴
' [注文履歴] o-- [決済金額]
' [注文履歴] o-- [注文ID]
' [注文履歴] o-- [注文日時]
' 注文も出るにすでに含まれるかも


' 出荷状況確認
' [出荷状況] o-- [出荷準備中]
[出荷状況] o-- [出荷待ち]
[出荷状況] o-- [出荷済み]
[出荷状況] o-- [キャンセル]
[出荷状況] o-- [差し戻し]

' 決済ログ
[決済ログ] o-- [決済ID]
[決済ログ] o-- [注文ID]
[決済ログ] o-- [ユーザーID]
[決済ログ] o-- [決済金額]
[決済ログ] o-- [決済日時]
[決済ログ] o-- [結果]
[結果] <|-- [成功] 
[結果] <|-- [失敗]







@enduml