@startuml bbショップドメインモデル図
skinparam componentStyle rectangle

' BBショップ
[管理者] o-- [BBショップ注文管理システム]
[管理者] o-- [管理者ID]
[管理者] o-- [管理者パスワード]
[BBショップ注文管理システム] o-- [BBショップWebサイト]
[BBショップWebサイト] o-- [決済サービス]
[決済サービス] -- [クレジット会社]
[BBショップWebサイト] o-- [顧客]
[BBショップWebサイト] o-- [商品]
[BBショップWebサイト] o-- [注文]
[BBショップWebサイト] o-- [工場]


[工場] -- [運送会社]
[顧客] -- [ユーザーID]
[顧客] -- [パスワード]
[顧客] -- [氏名]
[顧客] -- [住所]
[顧客] -- [メールアドレス]
[顧客] -- [電話番号]
[顧客] -- [クレジット情報]
[商品] -- [商品ID]
[商品] -- [商品情報]
[商品] -- [在庫数]
[注文] -- [注文番号]
[注文] -- [数量]
[注文] -- [注文日]
[注文] -- [合計金額]

@enduml
