@startuml RoboDogクラス図
skinparam classAttributeIconSize 0
hide circle

class RoboDog {
 -名前
 -時刻
 -挨拶
 -2つの整数

 +名前の取得()
 +名前の変更()
 +時刻の設定()
 +時刻に応じた挨拶の言葉を取得()
 +2つの整数を設定()
 +足し算結果取得()
}

class 挨拶 {
 -朝の挨拶
 -昼の挨拶
 -夜の挨拶

 +挨拶を取得()
}

class 2つの整数 {
 -1つ目の整数
 -2つ目の整数

 +足し算をする()
}

RoboDog o-- 挨拶
RoboDog o-- "2つの整数"
挨拶 o-- "朝の挨拶"
挨拶 o-- "昼の挨拶"
挨拶 o-- "夜の挨拶"
2つの整数 o-- "足し算をする"

@enduml