@startuml 会議室予約システムドメインモデル図
skinparam componentStyle rectangle

' 
[ユーザー] o-- [ユーザーID]
[ユーザー] o-- [ユーザー名]
[ユーザー] o-- [ログイン]
[ユーザー] o-- [ログアウト]

[ユーザー] o-- [会議室]
[会議室] <|-- [会議室名]
[会議室] <|-- [会議室情報]

[ユーザー] o-- [予約]
[予約] <|-- [予約番号]
[予約] <|-- [会議開始終了時刻]
[予約] <|-- [会議の目的]
[予約] <|-- [利用時刻]
[予約] <|-- [利用目的]
[予約] <|-- [日付]


@enduml