@startuml 訪問者システム新規登録シーケンス図
hide footbox
skinparam boundaryBackgroundColor #D5E8D4
skinparam controlBackgroundColor  #F8CECC
skinparam entityBackgroundColor   #DAE8FC

actor ユーザー as A
boundary 訪問者システム as B1
control 訪問者一覧表示 as C1
entity 訪問者 as E
boundary 訪問者一覧画面 as B2

A -> B1: 訪問者一覧をクリック()
activate A
activate B1


B1-> C1: 起動()
activate C1
C1 -> E: 訪問者情報一覧取得()
activate E
E --> C1:
deactivate E

C1 -> B2: 表示()
activate B2
deactivate B2

@enduml